services:
  employee_management_application_mysql:
    image: mysql:5.7
    container_name: employee_management_application_mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: employee_management_application
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root_pass
    ports:
      - "3307:3306" 
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
    driver: local

